/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Process;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.util.Optional;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
/**
 *
 * @author yuman
 */
public class CarSelection extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksi.Koneksi();
    
    public CarSelection() {
        initComponents();
        setLocationRelativeTo(null);
        title();
        showdata("");
        table2.setDefaultEditor(Object.class, null);
    }

    public void title() {
  Object[] title = {
    "License_plateid", "Status", "Brand", "Production", "Type", "Color", "Price"
  };
  tabModel = new DefaultTableModel(null, title);
  table2.setModel(tabModel);
}
    
    public void showdata(String where) {
  try {
    st = cn.createStatement();
    tabModel.getDataVector().removeAllElements();
    tabModel.fireTableDataChanged();
    rs = st.executeQuery("SELECT * FROM cartable Where Status like 'y' " + where);
    
    while (rs.next()) {
      Object[] data = {
        rs.getString("License_plateid"),
          rs.getString("Status"),
        rs.getString("Brand"),
        rs.getString("Production"),
        rs.getString("Type"),
         rs.getString("Color"),
        rs.getString("Price"),
      };
        tabModel.addRow(data);
    }
  } catch(Exception e) {
    e.printStackTrace();
  }
}
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLicense = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        production = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        txtOrderBY1 = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtProduction = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        price1 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        price2 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLicense.setEditable(false);
        jPanel1.add(txtLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 196, 174, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("ORDER BY");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 153, 106, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Car Selection");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 46, 262, 34));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LICENSE PLATE", "BRAND", "PRODUCTION YEAR", "TYPE", "COLOR", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 387, 785, 246));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4213475_arrow_back_left_return_icon.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 24, 58, 48));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("Car List");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 340, 101, -1));

        brand.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        brand.setText("LICENSE PLATE");
        jPanel1.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 200, -1, -1));

        production.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        production.setText("BRAND");
        jPanel1.add(production, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 240, 145, 28));

        type.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        type.setText("PRODUCTION");
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 281, 145, 28));

        color.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        color.setText("TYPE");
        jPanel1.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 153, -1, -1));

        price.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        price.setText("COLOR");
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 194, 104, 28));

        txtOrderBY1.setEditable(false);
        txtOrderBY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderBY1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrderBY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 149, 174, -1));

        txtBrand.setEditable(false);
        jPanel1.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 242, 174, -1));

        txtProduction.setEditable(false);
        jPanel1.add(txtProduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 283, 174, -1));

        txtType.setEditable(false);
        jPanel1.add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 149, 174, -1));

        txtColor.setEditable(false);
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 196, 174, -1));

        price1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        price1.setText("STATUS");
        jPanel1.add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 60, 30));

        txtStatus.setEditable(false);
        jPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 174, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/6934310_delivery_send_share_icon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 120, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/car2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 46, 66, -1));

        jLabel13.setText("Rp");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 245, 20, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 110));

        price2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        price2.setText("PRICE / DAY");
        jPanel1.add(price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 240, 104, 28));

        txtPrice1.setEditable(false);
        jPanel1.add(txtPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 242, 174, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
DefaultTableModel tblModel = (DefaultTableModel)table2.getModel();
        
        String data1 = tblModel.getValueAt(table2.getSelectedRow(),0).toString();
        String data2 = tblModel.getValueAt(table2.getSelectedRow(),1).toString();
        String data3 = tblModel.getValueAt(table2.getSelectedRow(),2).toString();
        String data4 = tblModel.getValueAt(table2.getSelectedRow(),3).toString();
        String data5 = tblModel.getValueAt(table2.getSelectedRow(),4).toString();
        String data6 = tblModel.getValueAt(table2.getSelectedRow(),5).toString();
        String data7 = tblModel.getValueAt(table2.getSelectedRow(),6).toString();
        
        txtLicense.setText(data1);
        txtStatus.setText(data2);
        txtBrand.setText(data3);
        txtProduction.setText(data4);
        txtType.setText(data5);
        txtColor.setText(data6);
        txtPrice1.setText(data7);  
        
        
        
            
        
    }//GEN-LAST:event_table2MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int dialogreturn = JOptionPane.showOptionDialog(this, "Are You Sure?", "Return",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);{

            if(dialogreturn == JOptionPane.YES_OPTION){
                CustomerInput jf1 = new CustomerInput();
                jf1.show();
                dispose();

                if (dialogreturn == JOptionPane.NO_OPTION){
                    remove(dialogreturn);
                }
            }
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txtOrderBY1.getText().equals("")||txtLicense.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Please Choose A Car !!");
        }else{
            
            int dialog = JOptionPane.showOptionDialog(this, "Are you Sure?", "Confirmation",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);{
                    
            if(dialog == JOptionPane.YES_OPTION){
            
                
            RentalTransaction a =new RentalTransaction();
            RentalTransaction.txtOrderby2.setText(txtOrderBY1.getText());
            RentalTransaction.txtLisense1.setText(txtLicense.getText());
            RentalTransaction.txtBrand1.setText(txtBrand.getText());
            RentalTransaction.txtType1.setText(txtType.getText());
            RentalTransaction.txtColor1.setText(txtColor.getText());
            RentalTransaction.txtYear1.setText(txtProduction.getText());
            RentalTransaction.txtPrice1.setText(txtPrice1.getText());
            RentalTransaction.txtStatus.setText(txtStatus.getText());
            a.setVisible(true);
            dispose();
            
            if (dialog == JOptionPane.NO_OPTION){
            
             remove(dialog); } 
            }
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtOrderBY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderBY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderBY1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brand;
    private javax.swing.JLabel color;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel price2;
    private javax.swing.JLabel production;
    private javax.swing.JTable table2;
    public static javax.swing.JTextField txtBrand;
    public static javax.swing.JTextField txtColor;
    public static javax.swing.JTextField txtLicense;
    public static javax.swing.JTextField txtOrderBY1;
    public static javax.swing.JTextField txtPrice1;
    public static javax.swing.JTextField txtProduction;
    public static javax.swing.JTextField txtStatus;
    public static javax.swing.JTextField txtType;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
