/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Process;

import static Process.CustomerInput.txtorder;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.lang.model.element.NestingKind;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yuman
 */
public class RentalTransaction extends javax.swing.JFrame{

     public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksi.Koneksi();
    
    public RentalTransaction() {
        initComponents();
        setLocationRelativeTo(null);
        autonumber1();
        
    }
     
   
    
    
    private void autonumber1() {
    try{
        Connection c = koneksi.Koneksi();
        Statement s = c.createStatement();
        String sql = "SELECT * FROM cartransaction ORDER BY Order_id DESC ";
        ResultSet r = s.executeQuery(sql);
        if (r.next()) {
            String NoID = r.getString("Order_id").substring(2);
            String ID = "" +(Integer.parseInt(NoID)+1);
            String Zero = "";
            
            if (ID.length()==1) 
                {Zero = "00";}
            else if (ID.length()==2)
                {Zero = "0";}    
            else if (ID.length()==3)
                {Zero = "";}
            txtOd.setText("OD" + Zero + ID);
        }   else{
            txtOd.setText("OD001");
        }
        r.close();
        s.close();
        } catch (Exception e){
            System.out.println("autonumber error");
    }   
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOrderby2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPay = new javax.swing.JTextField();
        cb_1 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtYear1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtChange = new javax.swing.JTextField();
        txtLisense1 = new javax.swing.JTextField();
        txtType1 = new javax.swing.JTextField();
        txtColor1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtBrand1 = new javax.swing.JTextField();
        txtOd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 178, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Transaction");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 210, 144));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("ORDER DATA NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 140, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("CAR DATA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, -1));

        txtOrderby2.setEditable(false);
        txtOrderby2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtOrderby2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 190, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("TOTAL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 60, -1));

        txtPrice1.setEditable(false);
        txtPrice1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 190, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("STATUS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 120, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("DATE OF RETURN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 120, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setText("MONEY CHANGE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 110, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel12.setText("ORDER DATA ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 140, -1));

        txtPay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayActionPerformed(evt);
            }
        });
        txtPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPayKeyPressed(evt);
            }
        });
        jPanel1.add(txtPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 290, 40));

        cb_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select Duration..", "1 Day", "2 Days", "3 Days" }));
        cb_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_1ActionPerformed(evt);
            }
        });
        jPanel1.add(cb_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 392, 210, 30));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4213475_arrow_back_left_return_icon.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 80, 60));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 41, 30));

        txtTotal.setEditable(false);
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTotalKeyPressed(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 290, 40));

        txtYear1.setEditable(false);
        txtYear1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtYear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 80, 30));

        jButton1.setText("=");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel9.setText("PAY");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 50, -1));

        txtChange.setEditable(false);
        txtChange.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtChange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChangeKeyPressed(evt);
            }
        });
        jPanel1.add(txtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 290, 40));

        txtLisense1.setEditable(false);
        txtLisense1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtLisense1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 190, 30));

        txtType1.setEditable(false);
        txtType1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 140, 30));

        txtColor1.setEditable(false);
        txtColor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 140, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/7340559_e-commerce_online_shopping_ui_receipt_icon.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 80, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/6934310_delivery_send_share_icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 600, 120, 50));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 24)); // NOI18N
        jLabel11.setText("Next Page");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, 130, -1));

        txtBrand1.setEditable(false);
        txtBrand1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBrand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 160, 30));

        txtOd.setEditable(false);
        jPanel1.add(txtOd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 190, 30));

        jLabel13.setText("Rp");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 20, -1));

        jLabel14.setText("Rp");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 20, -1));

        jLabel15.setText("Rp");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 20, -1));

        jLabel16.setText("Rp");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 20, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel17.setText("LOAN DURATION");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 120, -1));

        jLabel18.setText("___");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 396, 30, 20));

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 180, 30));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 180, 30));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel19.setText("LOAN DATE");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 80, -1));

        jPanel2.setBackground(new java.awt.Color(255, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 150));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel20.setText("PRICE");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 120, -1));

        txtStatus.setEditable(false);
        jPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int dialogreturn = JOptionPane.showOptionDialog(this, "Are You Sure?", "Return",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);{

            if(dialogreturn == JOptionPane.YES_OPTION){
                CustomerInput jf1 = new CustomerInput();
                jf1.show();
                dispose();

                if (dialogreturn == JOptionPane.NO_OPTION){
                    remove(dialogreturn);
                }
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
      
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyPressed
     
                                             
    }//GEN-LAST:event_txtTotalKeyPressed

    private void cb_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_1ActionPerformed
       
      int a=0;
      int c=0;
      a = Integer.parseInt(txtPrice1.getText());
      
      String pilih = (String) cb_1.getSelectedItem();
      
       if (pilih=="1 Day") {
            c = a*1;
            
     
        }else if (pilih=="2 Days") {
            c= a*2;
   
        }else if (pilih=="3 Days") {
            c= a*3; 
          
        }
      txtTotal.setText(Integer.toString(c));
        
    }//GEN-LAST:event_cb_1ActionPerformed

    private void txtPayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayKeyPressed
       String pay = txtPay.getText();
        int length = pay.length();
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<12){
                txtPay.setEditable(true);
            }else{
              txtPay.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE  ) {
             txtPay.setEditable(true);
             
            }else{
                txtPay.setEditable(false);
            }
            
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            txtPay.requestFocus();
    }//GEN-LAST:event_txtPayKeyPressed

    private void txtChangeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChangeKeyPressed
          String change = txtChange.getText();
        int length = change.length();
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<12){
                txtChange.setEditable(true);
            }else{
              txtChange.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE  ) {
            txtChange.setEditable(true);
             
            }else{
                txtChange.setEditable(false);
            }
            
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            txtChange.requestFocus();
    }//GEN-LAST:event_txtChangeKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        if (txtTotal.getText().equals("")|| txtPay.getText().equals("")|| cb_1.getSelectedItem().equals("Please Select Duration..")) {
            JOptionPane.showMessageDialog(this, "Please Fill The Required Info!!");
        }else{int a,b,c;
        a = Integer.parseInt(txtTotal.getText());
        b = Integer.parseInt(txtPay.getText());
            if (b<a) {
            JOptionPane.showMessageDialog(null, "Please Pay With The Right Amount!!");
        }else{
        c=b-a;
         this.txtChange.setText(Integer.toString(c));
        }
        }
        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if (txtChange.getText().equals("")|| jDateChooser1.getDate()==null || jDateChooser2.getDate()==null)  {
            JOptionPane.showMessageDialog(this,"Please Fill The Required Info !!");
        }else{
              
         
         String tampilan ="yyyy-MM-dd";
         SimpleDateFormat sdf = new SimpleDateFormat(tampilan);
         String date1 = String.valueOf(sdf.format(jDateChooser1.getDate()));
          String date2 = String.valueOf(sdf.format(jDateChooser2.getDate()));
          
          String jcalender=jDateChooser1.getDate().toString();
           String jcalender2=jDateChooser2.getDate().toString();
         
         String orderid = txtOd.getText().toString().trim();
         String ordername = txtOrderby2.getText().toString().trim();
       String licenseid = txtLisense1.getText().toString().trim();
       String status = txtStatus.getText().toString().trim();
       String brand = txtBrand1.getText().toString().trim();
       String production = txtYear1.getText().toString().trim();
       String type = txtType1.getText().toString().trim();
       String color = txtColor1.getText().toString().trim();
       String loandate = date1.toString().trim();
       String dateofreturn = date2.toString().trim();
        String price = txtPrice1.getText().toString().trim();
            try {
                Connection c = koneksi.Koneksi();
                String sql = "INSERT INTO cartransaction VALUES (?,?,?,?,?,?,?,?,?,?,?) ";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, orderid);
                p.setString(2, ordername);
                p.setString(3, licenseid);
                p.setString(4, brand);
                p.setString(5, production);
                p.setString(6, type);
                p.setString(7, color);
                p.setString(8, loandate);
                p.setString(9, dateofreturn);
                p.setString(10, price);
                p.setString(11, status);
                p.executeUpdate();
                p.close();
                
                //Update cartable
                
                String sql2 = "UPDATE cartable SET Status='n' Where License_plateid='"+(licenseid)+"'";
                PreparedStatement p2 = c.prepareStatement(sql2);
                
                
                
                p2.executeUpdate();
                p2.close();
                JOptionPane.showMessageDialog(this, "Transaction Successfull");

            } catch (Exception e) {
                System.out.println("Error");
            }
            finally{
                
            
        
                 Transcript jf1 = new Transcript();
                jf1.show();
                dispose();;                                                                        
            }
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
       
    }//GEN-LAST:event_jDateChooser1PropertyChange

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cb_1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    public static com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    public static javax.swing.JTextField txtBrand1;
    public static javax.swing.JTextField txtChange;
    public static javax.swing.JTextField txtColor1;
    public static javax.swing.JTextField txtLisense1;
    public static javax.swing.JTextField txtOd;
    public static javax.swing.JTextField txtOrderby2;
    public static javax.swing.JTextField txtPay;
    public static javax.swing.JTextField txtPrice1;
    public static javax.swing.JTextField txtStatus;
    public static javax.swing.JTextField txtTotal;
    public static javax.swing.JTextField txtType1;
    public static javax.swing.JTextField txtYear1;
    // End of variables declaration//GEN-END:variables
}

